// libc_version.h

#ifndef __LIBC_VERSION_H__
#define __LIBC_VERSION_H__

#define __LIBC_VERSION_MAJOR 0
#define __LIBC_VERSION_MINOR 9
#define __LIBC_VERSION_BUILD 4

// DO NOT MODIFY BELOW THIS LINE

#define MAKE_VERSION_STRING(M,m,b) #M "." #m "." #b
#define __LIBC_VERSION_STRING MAKE_VERSION_STRING(__LIBC_VERSION_MAJOR, __LIBC_VERSION_MINOR, __LIBC_VERSION_BUILD)
#define __LIBC_VERSION (100 * __LIBC_VERSION_MAJOR + 10 * __LIBC_VERSION_MINOR + __LIBC_VERSION_BUILD)


#endif // __LIBC_VERSION_H__
